<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>fileTypes</key>
        <array>
            <string>qml</string>
            <string>qmlproject</string>
        </array>
        <key>name</key>
        <string>QML</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>begin</key>
                <string>/\*(?!/)</string>
                <key>comment</key>
                <string>Block comment.</string>
                <key>end</key>
                <string>\*/</string>
                <key>name</key>
                <string>comment.block.documentation.qml</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>Line comment.</string>
                <key>match</key>
                <string>//.*$</string>
                <key>name</key>
                <string>comment.line.double-slash.qml</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>\b(import)\s+</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.import.qml</string>
                    </dict>
                </dict>
                <key>comment</key>
                <string>import statement.</string>
                <key>end</key>
                <string>$</string>
                <key>name</key>
                <string>meta.import.qml</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>entity.name.class.qml</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>constant.numeric.qml</string>
                            </dict>
                            <key>3</key>
                            <dict>
                                <key>name</key>
                                <string>keyword.other.import.qml</string>
                            </dict>
                            <key>4</key>
                            <dict>
                                <key>name</key>
                                <string>entity.name.class.qml</string>
                            </dict>
                        </dict>
                        <key>comment</key>
                        <string>import Namespace VersionMajor.VersionMinor [as SingletonTypeIdentifier]</string>
                        <key>match</key>
                        <string>([\w\d\.]+)\s+(\d+\.\d+)(?:\s+(as)\s+([A-Z][\w\d]*))?</string>
                        <key>name</key>
                        <string>meta.import.namespace.qml</string>
                    </dict>
                    <dict>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>string.quoted.double.qml</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>keyword.other.import.qml</string>
                            </dict>
                            <key>3</key>
                            <dict>
                                <key>name</key>
                                <string>entity.name.class.qml</string>
                            </dict>
                        </dict>
                        <key>comment</key>
                        <string>import &lt;string&gt; [as Script]</string>
                        <key>match</key>
                        <string>(\"[^\"]+\")(?:\s+(as)\s+([A-Z][\w\d]*))?</string>
                        <key>name</key>
                        <string>meta.import.dirjs.qml</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>comment</key>
                <string>Capitalized word (class or enum).</string>
                <key>match</key>
                <string>\b[A-Z]\w*\b</string>
                <key>name</key>
                <string>support.class.qml</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>onSomething - handler.</string>
                <key>match</key>
                <string>(((^|\{)\s*)|\b)on[A-Z]\w*\b</string>
                <key>name</key>
                <string>support.class.qml</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.qml</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>storage.modifier.qml</string>
                    </dict>
                </dict>
                <key>comment</key>
                <string>id: &lt;something&gt;</string>
                <key>match</key>
                <string>(?:^|\{)\s*(id)\s*\:\s*([^;\s]+)\b</string>
                <key>name</key>
                <string>meta.id.qml</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.qml</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.qml</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.qml</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>storage.type.qml</string>
                    </dict>
                    <key>5</key>
                    <dict>
                        <key>name</key>
                        <string>entity.other.attribute-name.qml</string>
                    </dict>
                </dict>
                <key>comment</key>
                <string>property definition.</string>
                <key>match</key>
                <string>^\s*(?:(default|readonly)\s+)?(property)\s+(?:(alias)|([\w\&lt;\&gt;]+))\s+(\w+)</string>
                <key>name</key>
                <string>meta.propertydef.qml</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>\b(signal)\s+(\w+)\s*</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.qml</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>support.function.qml</string>
                    </dict>
                </dict>
                <key>comment</key>
                <string>signal &lt;signalName&gt;[([&lt;type&gt; &lt;parameter&gt;[, ...]])]</string>
                <key>end</key>
                <string>;|(?=/)|$</string>
                <key>name</key>
                <string>meta.signal.qml</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>storage.type.qml</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>variable.parameter.qml</string>
                            </dict>
                        </dict>
                        <key>match</key>
                        <string>(\w+)\s+(\w+)</string>
                        <key>name</key>
                        <string>meta.signal.parameters.qml</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>constant.language.qml</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>storage.type.qml</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.qml</string>
                    </dict>
                </dict>
                <key>comment</key>
                <string>js keywords.</string>
                <key>match</key>
                <string>(?:\b|\s+)(?:(true|false|null|undefined)|(var|void)|(on|as|enum|connect|break|case|catch|continue|debugger|default|delete|do|else|finally|for|if|in|instanceof|new|return|switch|this|throw|try|typeof|while|with))\b</string>
                <key>name</key>
                <string>meta.keyword.qml</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>storage.type.qml</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.untitled</string>
                    </dict>
                </dict>
                <key>comment</key>
                <string>function definition.</string>
                <key>match</key>
                <string>\b(function)\s+([\w_]+)\s*(?=\()</string>
                <key>name</key>
                <string>meta.function.qml</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>function call.</string>
                <key>match</key>
                <string>\b[\w_]+\s*(?=\()</string>
                <key>name</key>
                <string>support.function.qml</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>property  (property: &lt;something&gt;).</string>
                <key>match</key>
                <string>(?:^|\{|;)\s*[a-z][\w\.]*\s*(?=\:)</string>
                <key>name</key>
                <string>entity.other.attribute-name.qml</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>property of the variable (name.property).</string>
                <key>match</key>
                <string>(?&lt;=\.)\b\w*</string>
                <key>name</key>
                <string>entity.other.attribute-name.qml</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>All non colored words are assumed to be variables.</string>
                <key>match</key>
                <string>\b([a-z_]\w*)\b</string>
                <key>name</key>
                <string>variable.parameter</string>
            </dict>
            <dict>
                <key>include</key>
                <string>source.js</string>
            </dict>
        </array>
        <key>scopeName</key>
        <string>source.qml</string>
        <key>uuid</key>
        <string>13a281e0-0507-45b4-bb6c-a57177630f10</string>
    </dict>
</plist>
