<?xml version="1.0" encoding="utf-8"?>
<!--
 Copyright (C) 2025 The Qt Company Ltd.
 SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0
-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>9.0</LangVersion>
    <IsTestProject>true</IsTestProject>
    <TargetFramework>net48</TargetFramework>

    <AssemblyName>Test_QtVsTools.Core</AssemblyName>
    <RootNamespace>QtVsTools.Test.Core</RootNamespace>

    <!-- We have an AssemblyInfo.cs -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <!-- We want to be explicit about the included files -->
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>

    <NoWarn>$(NoWarn);MSTEST0001;NU1603</NoWarn>
    <RunSettingsFile>$(SolutionDir)\vstools.runsettings</RunSettingsFile>

    <!-- Optional but helpful for binding redirects on net48 -->
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />

    <PackageReference Include="$(Name_MSTest_TestAdapter)" Version="$(Version_MSTest_TestAdapter)" />
    <PackageReference Include="$(Name_MSTest_TestFramework)" Version="$(Version_MSTest_TestFramework)" />

    <PackageReference Include="$(Name_Microsoft_Build)" Version="$(Version_Microsoft_Build)" />
    <PackageReference Include="$(Name_Microsoft_Build_Tasks_Core)" Version="$(Version_Microsoft_Build)" />

    <PackageReference Include="$(Name_Microsoft_VSSDK_BuildTools)" Version="$(Version_Microsoft_VSSDK_BuildTools)" />
    <PackageReference Include="$(Name_Microsoft_VisualStudio_SDK)" Version="$(Version_Microsoft_VisualStudio_SDK)" ExcludeAssets="runtime" />
  </ItemGroup>

  <Choose>
    <!-- VS 2026 / Dev18 -->
    <When Condition="'$(VisualStudioVersion)'=='18.0'">
      <ItemGroup>
        <PackageReference Include="Microsoft.ServiceHub.Framework" Version="4.8.55" />
        <PackageReference Include="Microsoft.VisualStudio.Sdk.TestFramework" Version="17.11.66" />
      </ItemGroup>
    </When>

    <!-- VS 2022 / Dev17 -->
    <When Condition="'$(VisualStudioVersion)'=='17.0'">
      <ItemGroup>
        <PackageReference Include="Microsoft.ServiceHub.Framework" Version="4.8.55" />
        <PackageReference Include="Microsoft.VisualStudio.Sdk.TestFramework" Version="17.11.66" />
      </ItemGroup>
    </When>

    <!-- VS 2019 / Dev16 -->
    <When Condition="'$(VisualStudioVersion)'=='16.0'">
      <ItemGroup>
        <PackageReference Include="Microsoft.VisualStudio.Sdk.TestFramework" Version="16.5.22-beta" />
      </ItemGroup>
    </When>
  </Choose>

  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)\QtVsTools.Core\QtVsTools.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Test_Concurrent.cs" />
    <Compile Include="Test_IdleTaskManager.cs" />
    <Compile Include="Test_LazyFactory.cs" />
    <Compile Include="Test_ProjectImporter.cs" />
    <Compile Include="Test_QmlLanguageServerManager.cs" />
    <Compile Include="Test_Utils.cs" />
    <Compile Include="Test_Utils.Zip.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="extension.vsixmanifest_TT">
      <DependsOn>$(SolutionDir)\common.tt</DependsOn>
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>extension.vsixmanifest</LastGenOutput>
    </None>

    <None Include="extension.vsixmanifest" Condition="Exists('extension.vsixmanifest')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Import Project="$(SolutionDir)\references.props" Condition="Exists('$(SolutionDir)\references.props')" />
  <Import Project="$(SolutionDir)\transform.targets" Condition="Exists('$(SolutionDir)\transform.targets')" />

</Project>
