######################################################################
# Automatically generated by qmake (2.00a) fr 29. jul 10:57:57 2005
######################################################################

TEMPLATE = app
TARGET = Qt4EEAddinTest 
DEPENDPATH += .
INCLUDEPATH += .

QT += xml network sql

# Input
SOURCES += main.cpp
