<?xml version="1.0" encoding="utf-8"?>
<!--
 Copyright (C) 2025 The Qt Company Ltd.
 SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0
-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>9.0</LangVersion>
    <IsTestProject>true</IsTestProject>
    <TargetFramework>net48</TargetFramework>

    <RootNamespace>Test_QtMsBuild.Build</RootNamespace>
    <AssemblyName>Test_QtMsBuild.Build</AssemblyName>

    <!-- We have an AssemblyInfo.cs -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <!-- We want to be explicit about the included files -->
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>

    <NoWarn>$(NoWarn);MSTEST0001</NoWarn>
    <RunSettingsFile>$(SolutionDir)\vstools.runsettings</RunSettingsFile>

    <!-- Optional but helpful for binding redirects on net48 -->
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="$(Name_MSTest_TestAdapter)" Version="$(Version_MSTest_TestAdapter)" />
    <PackageReference Include="$(Name_MSTest_TestFramework)" Version="$(Version_MSTest_TestFramework)" />

    <PackageReference Include="$(Name_Microsoft_Build)" Version="$(Version_Microsoft_Build)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)\QtMSBuild\QtMSBuild.csproj" />
    <ProjectReference Include="$(SolutionDir)\QtVsTools.Core\QtVsTools.Core.csproj" />
    <ProjectReference Include="$(SolutionDir)\QtVsTools.RegExpr\QtVsTools.RegExpr.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="BigSolution.cs" />
    <Compile Include="MsBuild.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="QTVSADDINBUG\Test_QTVSADDINBUG_1283.cs" />
    <Compile Include="QTVSADDINBUG\Test_QTVSADDINBUG_1289.cs" />
    <Compile Include="QTVSADDINBUG\Test_QTVSADDINBUG_1340.cs" />
    <Compile Include="TempProject.cs" />
    <Compile Include="Test_BigSolution.cs" />
    <Compile Include="Test_Build.cs" />
    <Compile Include="Test_Cpp20.cs" />
    <Compile Include="Test_Eval.cs" />
    <Compile Include="Test_IntDir.cs" />
    <Compile Include="Test_LateBinding.cs" />
    <Compile Include="Test_Pch.cs" />
    <Compile Include="Test_RcDefines.cs" />
    <Compile Include="Test_QmlStatic.cs" />
    <Compile Include="Test_StdAfx.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(SolutionDir)\EvalProps.cs">
      <Link>EvalProps.cs</Link>
    </Compile>
  </ItemGroup>

  <Import Project="$(SolutionDir)\references.props" Condition="Exists('$(SolutionDir)\references.props')" />
  <Import Project="$(SolutionDir)\transform.targets" Condition="Exists('$(SolutionDir)\transform.targets')" />
  <Import Project="$(SolutionDir)\EvalProps.targets" Condition="Exists('$(SolutionDir)\EvalProps.targets')" />

</Project>
