<?xml version="1.0" encoding="utf-8"?>
<!--
 Copyright (C) 2025 The Qt Company Ltd.
 SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0
-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>9.0</LangVersion>
    <IsTestProject>true</IsTestProject>
    <TargetFramework>net48</TargetFramework>

    <RootNamespace>Test_QtMsBuild.Tasks</RootNamespace>
    <AssemblyName>Test_QtMsBuild.Tasks</AssemblyName>

    <!-- We have an AssemblyInfo.cs -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <!-- We want to be explicit about the included files -->
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>

    <NoWarn>$(NoWarn);MSTEST0001</NoWarn>
    <RunSettingsFile>$(SolutionDir)\vstools.runsettings</RunSettingsFile>

    <!-- Optional but helpful for binding redirects on net48 -->
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="$(Name_MSTest_TestAdapter)" Version="$(Version_MSTest_TestAdapter)" />
    <PackageReference Include="$(Name_MSTest_TestFramework)" Version="$(Version_MSTest_TestFramework)" />

    <PackageReference Include="$(Name_Microsoft_VSSDK_BuildTools)" Version="$(Version_Microsoft_VSSDK_BuildTools)" />
    <PackageReference Include="$(Name_Microsoft_VisualStudio_SDK)" Version="$(Version_Microsoft_VisualStudio_SDK)" ExcludeAssets="runtime" />

    <PackageReference Include="$(Name_Microsoft_Build)" Version="$(Version_Microsoft_Build)" />
    <PackageReference Include="$(Name_Microsoft_Build_Tasks_Core)" Version="$(Version_Microsoft_Build)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)\QtMSBuild\QtMSBuild.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="MockBuildEngine.cs" />
    <Compile Include="MockTaskLogger.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Test_GetVarsFromMSBuild.cs" />
    <Compile Include="Test_Join.cs" />
    <Compile Include="Test_QtRunTask.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(SolutionDir)\EvalProps.cs">
      <Link>EvalProps.cs</Link>
    </Compile>
  </ItemGroup>

  <Import Project="$(SolutionDir)\references.props" Condition="Exists('$(SolutionDir)\references.props')" />
  <Import Project="$(SolutionDir)\transform.targets" Condition="Exists('$(SolutionDir)\transform.targets')" />
  <Import Project="$(SolutionDir)\EvalProps.targets" Condition="Exists('$(SolutionDir)\EvalProps.targets')" />

</Project>
